export type Role = "OWNER" | "ADMIN" | "OPERATOR" | "ANALYST" | "VIEWER";

export type Permission =
  | "READ_DASHBOARD"
  | "READ_AGENT"
  | "RUN_AGENT"
  | "UPLOAD_DOCS"
  | "ADMIN_CONTROLS";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  OWNER: ["READ_DASHBOARD", "READ_AGENT", "RUN_AGENT", "UPLOAD_DOCS", "ADMIN_CONTROLS"],
  ADMIN: ["READ_DASHBOARD", "READ_AGENT", "RUN_AGENT", "UPLOAD_DOCS", "ADMIN_CONTROLS"],
  OPERATOR: ["READ_DASHBOARD", "READ_AGENT", "RUN_AGENT", "UPLOAD_DOCS"],
  ANALYST: ["READ_DASHBOARD", "READ_AGENT"],
  VIEWER: ["READ_DASHBOARD"]
};
